export const SET_DOMAINS = 'SET_DOMAINS'
export const DELETE_DOMAINS = 'DELETE_DOMAINS'
export const SHOW_DOMAIN_LOADING = 'SHOW_DOMAIN_LOADING'
export const SET_DOMAINS_PAGINTATION = 'SET_DOMAINS_PAGINTATION'
